services:
  llmarket_db:
    image: postgres:latest
    volumes:
      - llmarket_db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file: .env

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres_db"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  llmarket_db_data: